# Generated by Django 4.2.15 on 2025-01-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workflow',
            field=models.CharField(blank=True, choices=[('PENDING_REVIEW', 'Pending_Review'), ('REVIEW_SCHEDULED', 'Review_Scheduled'), ('FEEDBACK_PROVIDED', 'Feedback_Provided'), ('UNDER_APPROVAL', 'Under_Approval'), ('REVIEW_APPROVED', 'Review_Approved'), ('REVIEW_REJECTED', 'Review_Rejected')], null=True, verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Hired on'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], null=True, verbose_name='Role'),
        ),
    ]
