# Generated by Django 4.2.17 on 2024-12-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('Manager', 'Manager'), ('EMPLOYEE', 'Employee')], null=True, verbose_name='Role'),
        ),
    ]
