# Generated by Django 4.2.15 on 2025-01-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_department_num_and_more'),
        ('accounts', '0002_employee_workflow_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='company.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='workflow',
            field=models.CharField(blank=True, choices=[('PENDING_REVIEW', 'Pending_Review'), ('REVIEW_SCHEDULED', 'Review_Scheduled'), ('FEEDBACK_PROVIDED', 'Feedback_Provided'), ('UNDER_APPROVAL', 'Under_Approval'), ('REVIEW_APPROVED', 'Review_Approved'), ('REVIEW_REJECTED', 'Review_Rejected')], max_length=200, null=True, verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], max_length=200, null=True, verbose_name='Role'),
        ),
    ]
