# Generated by Django 4.2.15 on 2025-01-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('department_num', models.PositiveIntegerField(verbose_name='Number of Departments')),
                ('employee_num', models.PositiveIntegerField(verbose_name='Number of Employees')),
                ('project_num', models.PositiveIntegerField(verbose_name='Number of Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Department Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_department', to='company.company')),
            ],
        ),
    ]
