# Generated by Django 4.2.15 on 2025-01-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='department_num',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_num',
        ),
        migrations.RemoveField(
            model_name='company',
            name='project_num',
        ),
    ]
